### ISSUE TITLE
[Bug]: Error in Laravel extension - Lumen

### ISSUE THREAD

**Issue by pieczarkazsolt** [laravel/vs-code-extension#34]
### Extension Version

0.1.11

### PHP Binary

Local PHP

### Operating System

macOS

### What happened?

The app crashes when I open a lumen project. Does the extension should also work with Lumen?
If I see correctly, it boots the app for certain things, could something be missing from Lumen? (e.g.:helpers, functions)

```
2024-12-16 23:42:52.252 [info] Activating Laravel Extension...
2024-12-16 23:42:52.252 [info] Started
2024-12-16 23:42:54.966 [error] 
2024-12-16 23:42:54.981 [error] 
2024-12-16 23:42:54.988 [error] 
2024-12-16 23:42:54.988 [error] 
2024-12-16 23:42:55.005 [error] 
2024-12-16 23:42:55.032 [error] 
2024-12-16 23:42:55.032 [error] 
2024-12-16 23:42:55.041 [error] 
2024-12-16 23:42:55.041 [error] 
2024-12-16 23:42:55.041 [error] 
2024-12-16 23:42:55.053 [error] 
2024-12-16 23:42:55.053 [error] 
2024-12-16 23:42:55.100 [error] Error:
 Configs

PHP Fatal error:  Uncaught Error: Call to undefined function config_path() in Command line code:27
Stack trace:
#0 {main}
  thrown in Command line code on line 27

2024-12-16 23:42:55.100 [error] /opt/local/bin/php -r "
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
\$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 \$local = collect(glob(config_path(\"/*.php\")))   ->merge(glob(config_path(\"**/*.php\")))   ->map(function (\$path) {     return [       (string) \Illuminate\Support\Str::of(\$path)         ->replace([config_path(\"/\"), \".php\"], \"\")         ->replace(\"/\", \".\"),       \$path     ];   });  \$vendor = collect(glob(base_path(\"vendor/**/**/config/*.php\")))->map(function (   \$path ) {   return [     (string) \Illuminate\Support\Str::of(\$path)       ->afterLast(\"/config/\")       ->replace(\".php\", \"\")       ->replace(\"/\", \".\"),     \$path   ]; });  \$configPaths = \$local   ->merge(\$vendor)   ->groupBy(0)   ->map(function (\$items) {     return \$items->pluck(1);   });  \$cachedContents = []; \$cachedParsed = [];  echo collect(\Illuminate\Support\Arr::dot(config()->all()))   ->map(function (\$value, \$key) use (\$configPaths) {     \$parts = explode(\".\", \$key);     \$toFind = \$key;     \$found = null;      while (count(\$parts) > 0) {       array_pop(\$parts);       \$toFind = implode(\".\", \$parts);        if (\$configPaths->has(\$toFind)) {         \$found = \$toFind;         break;       }     }      if (\$found === null) {       return null;     }      \$file = null;     \$line = null;      if (\$found === \$key) {       \$file = \$configPaths->get(\$found)[0];     } else {       foreach (\$configPaths->get(\$found) as \$path) {         \$cachedContents[\$path] ??= file_get_contents(\$path);         \$cachedParsed[\$path] ??= token_get_all(\$cachedContents[\$path]);          \$keysToFind = \Illuminate\Support\Str::of(\$key)           ->replaceFirst(\$found, \"\")           ->ltrim(\".\")           ->explode(\".\");          if (is_numeric(\$keysToFind->last())) {           \$index = \$keysToFind->pop();            if (\$index !== \"0\") {             return null;           }            \$key = collect(explode(\".\", \$key));           \$key->pop();           \$key = \$key->implode(\".\");           \$value = \"array(...)\";         }          \$nextKey = \$keysToFind->shift();         \$expectedDepth = 1;          \$depth = 0;          foreach (\$cachedParsed[\$path] as \$token) {           if (\$token === \"[\") {             \$depth++;           }            if (\$token === \"]\") {             \$depth--;           }            if (!is_array(\$token)) {             continue;           }            \$str = trim(\$token[1], '\"\\'');            if (             \$str === \$nextKey &&             \$depth === \$expectedDepth &&             \$token[0] === T_CONSTANT_ENCAPSED_STRING           ) {             \$nextKey = \$keysToFind->shift();             \$expectedDepth++;              if (\$nextKey === null) {               \$file = \$path;               \$line = \$token[2];               break;             }           }         }          if (\$file) {           break;         }       }     }      return [       \"name\" => \$key,       \"value\" => \$value,       \"file\" => \$file,       \"line\" => \$line     ];   })   ->filter()   ->values()   ->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
2024-12-16 23:42:55.100 [error] 
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists($this->app['log'], 'setHandlers')) {
            $this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 $local = collect(glob(config_path("/*.php")))   ->merge(glob(config_path("**/*.php")))   ->map(function ($path) {     return [       (string) \Illuminate\Support\Str::of($path)         ->replace([config_path("/"), ".php"], "")         ->replace("/", "."),       $path     ];   });  $vendor = collect(glob(base_path("vendor/**/**/config/*.php")))->map(function (   $path ) {   return [     (string) \Illuminate\Support\Str::of($path)       ->afterLast("/config/")       ->replace(".php", "")       ->replace("/", "."),     $path   ]; });  $configPaths = $local   ->merge($vendor)   ->groupBy(0)   ->map(function ($items) {     return $items->pluck(1);   });  $cachedContents = []; $cachedParsed = [];  echo collect(\Illuminate\Support\Arr::dot(config()->all()))   ->map(function ($value, $key) use ($configPaths) {     $parts = explode(".", $key);     $toFind = $key;     $found = null;      while (count($parts) > 0) {       array_pop($parts);       $toFind = implode(".", $parts);        if ($configPaths->has($toFind)) {         $found = $toFind;         break;       }     }      if ($found === null) {       return null;     }      $file = null;     $line = null;      if ($found === $key) {       $file = $configPaths->get($found)[0];     } else {       foreach ($configPaths->get($found) as $path) {         $cachedContents[$path] ??= file_get_contents($path);         $cachedParsed[$path] ??= token_get_all($cachedContents[$path]);          $keysToFind = \Illuminate\Support\Str::of($key)           ->replaceFirst($found, "")           ->ltrim(".")           ->explode(".");          if (is_numeric($keysToFind->last())) {           $index = $keysToFind->pop();            if ($index !== "0") {             return null;           }            $key = collect(explode(".", $key));           $key->pop();           $key = $key->implode(".");           $value = "array(...)";         }          $nextKey = $keysToFind->shift();         $expectedDepth = 1;          $depth = 0;          foreach ($cachedParsed[$path] as $token) {           if ($token === "[") {             $depth++;           }            if ($token === "]") {             $depth--;           }            if (!is_array($token)) {             continue;           }            $str = trim($token[1], '"\'');            if (             $str === $nextKey &&             $depth === $expectedDepth &&             $token[0] === T_CONSTANT_ENCAPSED_STRING           ) {             $nextKey = $keysToFind->shift();             $expectedDepth++;              if ($nextKey === null) {               $file = $path;               $line = $token[2];               break;             }           }         }          if ($file) {           break;         }       }     }      return [       "name" => $key,       "value" => $value,       "file" => $file,       "line" => $line     ];   })   ->filter()   ->values()   ->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);

2024-12-16 23:42:55.143 [error] 
2024-12-16 23:42:55.157 [error] 
2024-12-16 23:42:55.157 [error] 
2024-12-16 23:42:55.157 [error] 
2024-12-16 23:42:55.164 [error] 
2024-12-16 23:42:55.165 [error] 
2024-12-16 23:42:55.187 [error] 
2024-12-16 23:42:55.187 [error] 
2024-12-16 23:42:55.194 [error] 
2024-12-16 23:42:55.204 [error] 
2024-12-16 23:42:55.231 [error] 
2024-12-16 23:42:55.246 [error] 
2024-12-16 23:42:55.255 [error] 
2024-12-16 23:42:55.324 [error] Error:
 Middlewares

PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Http\Kernel] is not instantiable. in /Users/test/code/lumen-project/vendor/illuminate/container/Container.php:1089
Stack trace:
#0 /Users/test/code/lumen-project/vendor/illuminate/container/Container.php(886): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/test/code/lumen-project/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/test/code/lumen-project/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/test/code/lumen-project/vendor/laravel/lumen-framework/src/Application.php(300): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/test/code/lumen-project/vendor/laravel/lumen-framework/src/helpers.php(42): Laravel\Lumen\Application->make('Illuminate\\Cont...', Array)
#5 Command line code(27): app('Illuminate\\Cont...')
#6 {main}
  thrown in /Users/test/code/lumen-project/vendor/illuminate/container/Container.php on line 1089

2024-12-16 23:42:55.324 [error] /opt/local/bin/php -r "
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
\$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 echo collect(app(\"Illuminate\Contracts\Http\Kernel\")->getMiddlewareGroups())   ->merge(app(\"Illuminate\Contracts\Http\Kernel\")->getRouteMiddleware())   ->map(function (\$middleware, \$key) {     \$result = [       \"class\" => null,       \"uri\" => null,       \"startLine\" => null,       \"parameters\" => null,       \"groups\" => [],     ];      if (is_array(\$middleware)) {       \$result[\"groups\"] = collect(\$middleware)->map(function (\$m) {         if (!class_exists(\$m)) {           return [             \"class\" => \$m,             \"uri\" => null,             \"startLine\" => null           ];         }          \$reflected = new ReflectionClass(\$m);         \$reflectedMethod = \$reflected->getMethod(\"handle\");          return [           \"class\" => \$m,           \"uri\" => \$reflected->getFileName(),           \"startLine\" =>               \$reflectedMethod->getFileName() === \$reflected->getFileName()               ? \$reflectedMethod->getStartLine()               : null         ];       })->all();        return \$result;     }      \$reflected = new ReflectionClass(\$middleware);     \$reflectedMethod = \$reflected->getMethod(\"handle\");      \$result = array_merge(\$result, [       \"class\" => \$middleware,       \"uri\" => \$reflected->getFileName(),       \"startLine\" => \$reflectedMethod->getStartLine(),     ]);      \$parameters = collect(\$reflectedMethod->getParameters())       ->filter(function (\$rc) {         return \$rc->getName() !== \"request\" && \$rc->getName() !== \"next\";       })       ->map(function (\$rc) {         return \$rc->getName() . (\$rc->isVariadic() ? \"...\" : \"\");       });      if (\$parameters->isEmpty()) {       return \$result;     }      return array_merge(\$result, [       \"parameters\" => \$parameters->implode(\",\")     ]);   })   ->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
2024-12-16 23:42:55.324 [error] 
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists($this->app['log'], 'setHandlers')) {
            $this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 echo collect(app("Illuminate\Contracts\Http\Kernel")->getMiddlewareGroups())   ->merge(app("Illuminate\Contracts\Http\Kernel")->getRouteMiddleware())   ->map(function ($middleware, $key) {     $result = [       "class" => null,       "uri" => null,       "startLine" => null,       "parameters" => null,       "groups" => [],     ];      if (is_array($middleware)) {       $result["groups"] = collect($middleware)->map(function ($m) {         if (!class_exists($m)) {           return [             "class" => $m,             "uri" => null,             "startLine" => null           ];         }          $reflected = new ReflectionClass($m);         $reflectedMethod = $reflected->getMethod("handle");          return [           "class" => $m,           "uri" => $reflected->getFileName(),           "startLine" =>               $reflectedMethod->getFileName() === $reflected->getFileName()               ? $reflectedMethod->getStartLine()               : null         ];       })->all();        return $result;     }      $reflected = new ReflectionClass($middleware);     $reflectedMethod = $reflected->getMethod("handle");      $result = array_merge($result, [       "class" => $middleware,       "uri" => $reflected->getFileName(),       "startLine" => $reflectedMethod->getStartLine(),     ]);      $parameters = collect($reflectedMethod->getParameters())       ->filter(function ($rc) {         return $rc->getName() !== "request" && $rc->getName() !== "next";       })       ->map(function ($rc) {         return $rc->getName() . ($rc->isVariadic() ? "..." : "");       });      if ($parameters->isEmpty()) {       return $result;     }      return array_merge($result, [       "parameters" => $parameters->implode(",")     ]);   })   ->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);

2024-12-16 23:42:55.337 [error] Error:
 App Bindings

PHP Fatal error:  Uncaught Error: Call to a member function getFileName() on null in Command line code:27
Stack trace:
#0 [internal function]: {closure}(Array, 'Illuminate\\Cont...')
#1 /Users/test/code/lumen-project/vendor/illuminate/collections/Collection.php(695): array_map(Object(Closure), Array, Array)
#2 /Users/test/code/lumen-project/vendor/illuminate/collections/Traits/EnumeratesValues.php(354): Illuminate\Support\Collection->map(Object(Closure))
#3 Command line code(27): Illuminate\Support\Collection->flatMap(Object(Closure))
#4 {main}
  thrown in Command line code on line 27

2024-12-16 23:42:55.337 [error] /opt/local/bin/php -r "
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
\$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 echo collect(app()->getBindings())     ->filter(fn (\$binding) => (\$binding['concrete'] ?? null) !== null)     ->flatMap(function (\$binding, \$key) {         \$boundTo = new ReflectionFunction(\$binding['concrete']);          \$closureClass = \$boundTo->getClosureScopeClass();          return [             \$key => [                 'uri' => \$closureClass->getFileName(),                 'class' => \$closureClass->getName(),                 'startLine' => \$boundTo->getStartLine(),             ],         ];     })->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
2024-12-16 23:42:55.338 [error] 
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists($this->app['log'], 'setHandlers')) {
            $this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 echo collect(app()->getBindings())     ->filter(fn ($binding) => ($binding['concrete'] ?? null) !== null)     ->flatMap(function ($binding, $key) {         $boundTo = new ReflectionFunction($binding['concrete']);          $closureClass = $boundTo->getClosureScopeClass();          return [             $key => [                 'uri' => $closureClass->getFileName(),                 'class' => $closureClass->getName(),                 'startLine' => $boundTo->getStartLine(),             ],         ];     })->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);

2024-12-16 23:42:55.620 [error] Error:
 HTTP Routes

PHP Fatal error:  Uncaught Error: Call to a member function getRoutes() on array in Command line code:27
Stack trace:
#0 {main}
  thrown in Command line code on line 27

2024-12-16 23:42:55.620 [error] /opt/local/bin/php -r "
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
\$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 function vsCodeGetRouterReflection(\Illuminate\Routing\Route \$route) {     if (\$route->getActionName() === 'Closure') {         return new \ReflectionFunction(\$route->getAction()['uses']);     }      if (!str_contains(\$route->getActionName(), '@')) {         return new \ReflectionClass(\$route->getActionName());     }      try {         return new \ReflectionMethod(\$route->getControllerClass(), \$route->getActionMethod());     } catch (\Throwable \$e) {         \$namespace = app(\Illuminate\Routing\UrlGenerator::class)->getRootControllerNamespace()             ?? (app()->getNamespace() . 'Http\\Controllers');          return new \ReflectionMethod(             \$namespace . '\\\' . ltrim(\$route->getControllerClass(), '\\\'),             \$route->getActionMethod(),         );     } }  echo collect(app('router')->getRoutes()->getRoutes())     ->map(function (\Illuminate\Routing\Route \$route) {         try {             \$reflection = vsCodeGetRouterReflection(\$route);         } catch (\Throwable \$e) {             \$reflection = null;         }          return [             'method' => collect(\$route->methods())->filter(function (\$method) {                 return \$method !== 'HEAD';             })->implode('|'),             'uri' => \$route->uri(),             'name' => \$route->getName(),             'action' => \$route->getActionName(),             'parameters' => \$route->parameterNames(),             'filename' => \$reflection ? \$reflection->getFileName() : null,             'line' => \$reflection ? \$reflection->getStartLine() : null,         ];     })     ->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
2024-12-16 23:42:55.620 [error] 
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists($this->app['log'], 'setHandlers')) {
            $this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 function vsCodeGetRouterReflection(\Illuminate\Routing\Route $route) {     if ($route->getActionName() === 'Closure') {         return new \ReflectionFunction($route->getAction()['uses']);     }      if (!str_contains($route->getActionName(), '@')) {         return new \ReflectionClass($route->getActionName());     }      try {         return new \ReflectionMethod($route->getControllerClass(), $route->getActionMethod());     } catch (\Throwable $e) {         $namespace = app(\Illuminate\Routing\UrlGenerator::class)->getRootControllerNamespace()             ?? (app()->getNamespace() . 'Http\\Controllers');          return new \ReflectionMethod(             $namespace . '\\' . ltrim($route->getControllerClass(), '\\'),             $route->getActionMethod(),         );     } }  echo collect(app('router')->getRoutes()->getRoutes())     ->map(function (\Illuminate\Routing\Route $route) {         try {             $reflection = vsCodeGetRouterReflection($route);         } catch (\Throwable $e) {             $reflection = null;         }          return [             'method' => collect($route->methods())->filter(function ($method) {                 return $method !== 'HEAD';             })->implode('|'),             'uri' => $route->uri(),             'name' => $route->getName(),             'action' => $route->getActionName(),             'parameters' => $route->parameterNames(),             'filename' => $reflection ? $reflection->getFileName() : null,             'line' => $reflection ? $reflection->getStartLine() : null,         ];     })     ->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);

2024-12-16 23:42:55.715 [error] Error:
 Custom Blade Directives

PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #1 [ <required> $cachePath ]] in class Illuminate\View\Compilers\Compiler in /Users/test/code/lumen-project/vendor/illuminate/container/Container.php:1104
Stack trace:
#0 /Users/test/code/lumen-project/vendor/illuminate/container/Container.php(1011): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter))
#1 /Users/test/code/lumen-project/vendor/illuminate/container/Container.php(946): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#2 /Users/test/code/lumen-project/vendor/illuminate/container/Container.php(908): Illuminate\Container\Container->resolveDependencies(Array)
#3 /Users/test/code/lumen-project/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build('Illuminate\\View...')
#4 /Users/test/code/lumen-project/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve('Illuminate\\View...', Array)
#5 /Users/test/code/lumen-project/vendor/laravel/lumen-framework/src/Application.php(300): Illuminate\Container\Container->make('Illuminate\\View...', Array)
#6 /Users/test/code/lumen-project/vendor/laravel/lumen-framework/src/helpers.php(42): Laravel\Lumen\Application->make('Illuminate\\View...', Array)
#7 Command line code(27): app('Illuminate\\View...')
#8 {main}
  thrown in /Users/test/code/lumen-project/vendor/illuminate/container/Container.php on line 1104

2024-12-16 23:42:55.715 [error] /opt/local/bin/php -r "
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
\$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 echo collect(app(Illuminate\View\Compilers\BladeCompiler::class)->getCustomDirectives())     ->map(function (\$customDirective, \$name) {         if (\$customDirective instanceof \Closure) {             return [                 'name' => \$name,                 'hasParams' => (new ReflectionFunction(\$customDirective))->getNumberOfParameters() >= 1,             ];         }          if (is_array(\$customDirective)) {             return [                 'name' => \$name,                 'hasParams' => (new ReflectionMethod(\$customDirective[0], \$customDirective[1]))->getNumberOfParameters() >= 1,             ];         }          return null;     })     ->filter()     ->values()     ->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
2024-12-16 23:42:55.715 [error] 
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists($this->app['log'], 'setHandlers')) {
            $this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 echo collect(app(Illuminate\View\Compilers\BladeCompiler::class)->getCustomDirectives())     ->map(function ($customDirective, $name) {         if ($customDirective instanceof \Closure) {             return [                 'name' => $name,                 'hasParams' => (new ReflectionFunction($customDirective))->getNumberOfParameters() >= 1,             ];         }          if (is_array($customDirective)) {             return [                 'name' => $name,                 'hasParams' => (new ReflectionMethod($customDirective[0], $customDirective[1]))->getNumberOfParameters() >= 1,             ];         }          return null;     })     ->filter()     ->values()     ->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);

2024-12-16 23:42:55.864 [error] Error:
 Paths

PHP Fatal error:  Uncaught Error: Call to undefined function config_path() in Command line code:27
Stack trace:
#0 {main}
  thrown in Command line code on line 27

2024-12-16 23:42:55.864 [error] /opt/local/bin/php -r "
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
\$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
             echo json_encode([                 [                     'key' => 'base_path',                     'path' => base_path(),                 ],                 [                     'key' => 'resource_path',                     'path' => resource_path(),                 ],                 [                     'key' => 'config_path',                     'path' => config_path(),                 ],                 [                     'key' => 'app_path',                     'path' => app_path(),                 ],                 [                     'key' => 'database_path',                     'path' => database_path(),                 ],                 [                     'key' => 'lang_path',                     'path' => lang_path(),                 ],                 [                     'key' => 'public_path',                     'path' => public_path(),                 ],                 [                     'key' => 'storage_path',                     'path' => storage_path(),                 ],         ]);         ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
2024-12-16 23:42:55.864 [error] 
define('LARAVEL_START', microtime(true));

require_once '/Users/test/code/lumen-project/vendor/autoload.php';
$app = require_once '/Users/test/code/lumen-project/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists($this->app['log'], 'setHandlers')) {
            $this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
             echo json_encode([                 [                     'key' => 'base_path',                     'path' => base_path(),                 ],                 [                     'key' => 'resource_path',                     'path' => resource_path(),                 ],                 [                     'key' => 'config_path',                     'path' => config_path(),                 ],                 [                     'key' => 'app_path',                     'path' => app_path(),                 ],                 [                     'key' => 'database_path',                     'path' => database_path(),                 ],                 [                     'key' => 'lang_path',                     'path' => lang_path(),                 ],                 [                     'key' => 'public_path',                     'path' => public_path(),                 ],                 [                     'key' => 'storage_path',                     'path' => storage_path(),                 ],         ]);         ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
```

**Comment by pieczarkazsolt** [comment]
Hey @joetannenbaum, is there any update on it?

**Comment by TitasGailius** [comment]
Thanks for reporting this.

The extension relies on parts of the Laravel application structure and helper functions that are not available in Lumen, which is why it falls over in cases like this.  ￼

I’m going to close this for now, but thanks again for reporting it.
