### ISSUE TITLE
[Bug]: [error] php-parser-0.1.6: Exec format error

### ISSUE THREAD

**Issue by joseph-d** [laravel/vs-code-extension#56]
### Extension Version

v0.1.11

### PHP Binary

Sail

### Operating System

Linux

### What happened?
```
2024-12-17 08:29:17.940 [info] Activating Laravel Extension...
2024-12-17 08:29:17.940 [info] Started
2024-12-17 08:29:17.940 [error] /bin/sh: 1: /home/sail/.vscode-server/data/User/globalStorage/laravel.vscode-laravel/file-downloader-downloads/php-parser-0.1.6: Exec format error

2024-12-17 08:29:21.067 [error] Error:
 Translation namespaces

__VSCODE_LARAVEL_START_OUTPUT__{"auth.failed":{"en":{"value":"These credentials do not match our records.","path":"\/var\/www\/html\/lang\/en\/auth.php","line":16,"params":[]},"default":{"value":"These credentials do not match our records.","path":"\/var\/www\/html\/lang\/en\/auth.php","line":16,"params":[]}},"auth.password":{"en":{"value":"The provided password is incorrect.","path":"\/var\/www\/html\/lang\/en\/auth.php","line":17,"params":[]},"default":{"value":"The provided password is incorrect."

----- TRUNCATED ----

2024-12-17 08:29:21.069 [error] /usr/bin/php -r "
define('LARAVEL_START', microtime(true));

require_once '/var/www/html/vendor/autoload.php';
\$app = require_once '/var/www/html/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 function vsCodeTranslationValue(\$key, \$value, \$file, \$lines): array {     \$lineNumber = 1;     \$keys = explode('.', \$key);     \$index = 0;     \$currentKey = array_shift(\$keys);      while (\$currentKey !== null && \$index < count(\$lines)) {         \$line = \$lines[\$index][1];          if (strpos(\$line, '\"' . \$currentKey . '\"', 0) !== false || strpos(\$line, \"'\" . \$currentKey . \"'\", 0) !== false) {             \$lineNumber = \$lines[\$index][0];             \$currentKey = array_shift(\$keys);         }          \$index++;     }      return [         'value' => \$value,         'path' => realpath(\$file),         'line' => \$lineNumber,         'params' => preg_match_all('/\:([A-Za-z0-9_]+)/', \$value, \$matches) ? \$matches[1] : [],     ]; }  function vscodeCollectTranslations(string \$path, string \$namespace = null) {     return collect(glob(\"{\$path}/**/*.{php,json}\", GLOB_BRACE))->map(function (\$file) use (\$path, \$namespace) {         \$key = pathinfo(\$file, PATHINFO_FILENAME);          if (\$namespace) {             \$key = \"{\$namespace}::{\$key}\";         }          \$lang = collect(explode('/', str_replace(\$path, '', \$file)))->filter()->first();          \$fileLines = explode(PHP_EOL, file_get_contents(\$file));         \$lines = [];         \$inComment = false;          foreach (\$fileLines as \$index => \$line) {             \$trimmed = trim(\$line);              if (substr(\$trimmed, 0, 2) === '/*') {                 \$inComment = true;                 continue;             }              if (\$inComment) {                 if (substr(\$trimmed, -2) !== '*/') {                     continue;                 }                  \$inComment = false;             }              if (substr(\$trimmed, 0, 2) === '//') {                 continue;             }              \$lines[] = [\$index + 1, \$trimmed];         }          return [             'key' => \$key,             'lang' => \$lang,             'values' => collect(\Illuminate\Support\Arr::dot(__(\$key, [], \$lang)))->map(function (\$value, \$key) use (\$file, \$lines) {                 if (is_array(\$value)) {                     return null;                 }                  return vsCodeTranslationValue(\$key, \$value, \$file, \$lines);             })->filter(),         ];     }); }  \$loader = app(\"translator\")->getLoader(); \$namespaces = \$loader->namespaces();  \$reflection = new ReflectionClass(\$loader); \$property = \$reflection->hasProperty(\"paths\")   ? \$reflection->getProperty(\"paths\")   : \$reflection->getProperty(\"path\"); \$property->setAccessible(true);  \$paths = \Illuminate\Support\Arr::wrap(\$property->getValue(\$loader));  \$default = collect(\$paths)->flatMap(function (\$path) {   return vscodeCollectTranslations(\$path); });  \$namespaced = collect(\$namespaces)->flatMap(function (\$path, \$namespace) {     return vscodeCollectTranslations(\$path, \$namespace); });  \$final = [];  foreach (\$default->merge(\$namespaced) as \$value) {     foreach (\$value['values'] as \$key => \$v) {         \$dotKey = \"{\$value['key']}.{\$key}\";          if (!isset(\$final[\$dotKey])) {             \$final[\$dotKey] = [];         }          \$final[\$dotKey][\$value['lang']] = \$v;          if (\$value['lang'] === \Illuminate\Support\Facades\App::currentLocale()) {             \$final[\$dotKey]['default'] = \$v;         }     } }  echo json_encode(\$final); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
2024-12-17 08:29:21.069 [error] 
define('LARAVEL_START', microtime(true));

require_once '/var/www/html/vendor/autoload.php';
$app = require_once '/var/www/html/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
        //
    }

    public function boot()
    {
        if (method_exists($this->app['log'], 'setHandlers')) {
            $this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 function vsCodeTranslationValue($key, $value, $file, $lines): array {     $lineNumber = 1;     $keys = explode('.', $key);     $index = 0;     $currentKey = array_shift($keys);      while ($currentKey !== null && $index < count($lines)) {         $line = $lines[$index][1];          if (strpos($line, '"' . $currentKey . '"', 0) !== false || strpos($line, "'" . $currentKey . "'", 0) !== false) {             $lineNumber = $lines[$index][0];             $currentKey = array_shift($keys);         }          $index++;     }      return [         'value' => $value,         'path' => realpath($file),         'line' => $lineNumber,         'params' => preg_match_all('/\:([A-Za-z0-9_]+)/', $value, $matches) ? $matches[1] : [],     ]; }  function vscodeCollectTranslations(string $path, string $namespace = null) {     return collect(glob("{$path}/**/*.{php,json}", GLOB_BRACE))->map(function ($file) use ($path, $namespace) {         $key = pathinfo($file, PATHINFO_FILENAME);          if ($namespace) {             $key = "{$namespace}::{$key}";         }          $lang = collect(explode('/', str_replace($path, '', $file)))->filter()->first();          $fileLines = explode(PHP_EOL, file_get_contents($file));         $lines = [];         $inComment = false;          foreach ($fileLines as $index => $line) {             $trimmed = trim($line);              if (substr($trimmed, 0, 2) === '/*') {                 $inComment = true;                 continue;             }              if ($inComment) {                 if (substr($trimmed, -2) !== '*/') {                     continue;                 }                  $inComment = false;             }              if (substr($trimmed, 0, 2) === '//') {                 continue;             }              $lines[] = [$index + 1, $trimmed];         }          return [             'key' => $key,             'lang' => $lang,             'values' => collect(\Illuminate\Support\Arr::dot(__($key, [], $lang)))->map(function ($value, $key) use ($file, $lines) {                 if (is_array($value)) {                     return null;                 }                  return vsCodeTranslationValue($key, $value, $file, $lines);             })->filter(),         ];     }); }  $loader = app("translator")->getLoader(); $namespaces = $loader->namespaces();  $reflection = new ReflectionClass($loader); $property = $reflection->hasProperty("paths")   ? $reflection->getProperty("paths")   : $reflection->getProperty("path"); $property->setAccessible(true);  $paths = \Illuminate\Support\Arr::wrap($property->getValue($loader));  $default = collect($paths)->flatMap(function ($path) {   return vscodeCollectTranslations($path); });  $namespaced = collect($namespaces)->flatMap(function ($path, $namespace) {     return vscodeCollectTranslations($path, $namespace); });  $final = [];  foreach ($default->merge($namespaced) as $value) {     foreach ($value['values'] as $key => $v) {         $dotKey = "{$value['key']}.{$key}";          if (!isset($final[$dotKey])) {             $final[$dotKey] = [];         }          $final[$dotKey][$value['lang']] = $v;          if ($value['lang'] === \Illuminate\Support\Facades\App::currentLocale()) {             $final[$dotKey]['default'] = $v;         }     } }  echo json_encode($final); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
```

### Mimimal Code Sample

```php
Seems to happen as soon as any PHP file is opened.
```

**Comment by joetannenbaum** [comment]
We just released 0.1.12, can you verify if is this still happening?

**Comment by davidarlddi** [comment]
yas there still error in v0.1.12

```sh
2024-12-18 09:27:35.861 [error] Error:
 Translation namespaces

__VSCODE_LARAVEL_START_OUTPUT__
   Symfony\Component\ErrorHandler\Error\FatalError 

  Uncaught Error: Undefined constant "GLOB_BRACE" in Command line code:28
Stack trace:
#0 Command line code(28): vscodeCollectTranslations('/home/david/Pro...')
#1 [internal function]: {closure}('/home/david/Pro...', 0)
#2 /home/david/Projects/voksel/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(609): array_map(Object(Closure), Array, Array)
#3 /home/david/Projects/voksel/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(795): Illuminate\Support\Arr::map(Array, Object(Closure))
#4 /home/david/Projects/voksel/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(427): Illuminate\Support\Collection->map(Object(Closure))
#5 Command line code(28): Illuminate\Support\Collection->flatMap(Object(Closure))
#6 {main}
  thrown
```

**Comment by joseph-d** [comment]
> We just released 0.1.12, can you verify if is this still happening?

The error is no longer happening for me on v0.1.12

**Comment by NikolajLauritsen** [comment]
The same Error also happens for me in v0.1.12.

**Comment by joseph-d** [comment]
I've updated the title to a more specific error (actually the first error in the output) to avoid other reports being associated
