### ISSUE TITLE
[Bug]:  PHP File is opened, the extension is not able to run

### ISSUE THREAD

**Issue by marcosgrimm** [laravel/vs-code-extension#84]
### Extension Version

0.1.12

### PHP Binary

Herd

### Operating System

macOS

### What happened?

When a PHP File is opened, the extension is not able to run

2024-12-18 12:04:44.720 [info] Activating Laravel Extension...
2024-12-18 12:04:44.720 [info] Started
2024-12-18 12:04:46.014 [error] Error:
 App Bindings

__VSCODE_LARAVEL_START_OUTPUT__
   Symfony\Component\ErrorHandler\Error\FatalError 

  Uncaught Error: Call to a member function getFileName() on null in Command line code:28
Stack trace:
#0 [internal function]: {closure}(Array, 'Faker\\Generator...')
#1 ****/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(605): array_map(Object(Closure), Array, Array)
#2 ****/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(791): Illuminate\Support\Arr::map(Array, Object(Closure))
#3 ****vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(427): Illuminate\Support\Collection->map(Object(Closure))
#4 Command line code(28): Illuminate\Support\Collection->flatMap(Object(Closure))
#5 {main}
  thrown

  at Command line code:28

2024-12-18 12:04:46.014 [error] /****/Library/Application\ Support/Herd/bin//php -r "
error_reporting(E_ERROR | E_PARSE);

define('LARAVEL_START', microtime(true));

require_once '****/vendor/autoload.php';
\$app = require_once '****/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
    }

    public function boot()
    {
        if (method_exists(\$this->app['log'], 'setHandlers')) {
            \$this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

\$app->register(new VsCodeLaravel(\$app));
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 echo collect(app()->getBindings())     ->filter(fn (\$binding) => (\$binding['concrete'] ?? null) !== null)     ->flatMap(function (\$binding, \$key) {         \$boundTo = new ReflectionFunction(\$binding['concrete']);          \$closureClass = \$boundTo->getClosureScopeClass();          return [             \$key => [                 'uri' => \$closureClass->getFileName(),                 'class' => \$closureClass->getName(),                 'startLine' => \$boundTo->getStartLine(),             ],         ];     })->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);
"
2024-12-18 12:04:46.014 [error] 
error_reporting(E_ERROR | E_PARSE);

define('LARAVEL_START', microtime(true));

require_once '****/vendor/autoload.php';
$app = require_once '****/bootstrap/app.php';

class VsCodeLaravel extends \Illuminate\Support\ServiceProvider
{
    public function register()
    {
    }

    public function boot()
    {
        if (method_exists($this->app['log'], 'setHandlers')) {
            $this->app['log']->setHandlers([new \Monolog\Handler\ProcessHandler()]);
        }
    }
}

$app->register(new VsCodeLaravel($app));
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

echo '__VSCODE_LARAVEL_START_OUTPUT__';
 echo collect(app()->getBindings())     ->filter(fn ($binding) => ($binding['concrete'] ?? null) !== null)     ->flatMap(function ($binding, $key) {         $boundTo = new ReflectionFunction($binding['concrete']);          $closureClass = $boundTo->getClosureScopeClass();          return [             $key => [                 'uri' => $closureClass->getFileName(),                 'class' => $closureClass->getName(),                 'startLine' => $boundTo->getStartLine(),             ],         ];     })->toJson(); ;
echo '__VSCODE_LARAVEL_END_OUTPUT__';

exit(0);

**Comment by themahdavi** [comment]
same on my machine 
Macbook pro M1pro MacOS 15.2

**Comment by marcosgrimm** [comment]
Still the same on version 0.1.14

**Comment by marcosgrimm** [comment]
Different error on version 0.1.15:
```

2025-01-07 09:31:03.427 [info] Activating Laravel Extension...
2025-01-07 09:31:03.427 [info] Started
2025-01-07 09:31:04.070 [error] App Bindings

Error: App Bindings

__VSCODE_LARAVEL_START_OUTPUT__
   Error 

  Call to a member function getFileName() on null

  at vendor/_laravel_ide/discover-d4f39ea8c8afd10ce595be32bd60d7a7.php:40
     36▕         $closureClass = $boundTo->getClosureScopeClass();
     37▕ 
     38▕         return [
     39▕             $key => [
  ➜  40▕                 'uri' => $closureClass->getFileName(),
     41▕                 'class' => $closureClass->getName(),
     42▕                 'startLine' => $boundTo->getStartLine(),
     43▕             ],
     44▕         ];

  1   [internal]:0

```

**Comment by marcosgrimm** [comment]
Another error on v 0.1.15:

```
2025-01-07 09:31:49.630 [error] 
In ScopedPropertyAccessExpressionParser.php line 20:
                                                                               
  Call to undefined method Microsoft\PhpParser\Node\Expression\Variable::getR  
  esolvedName()                

```

**Comment by marcosgrimm** [comment]
Still happening on v0.1.16

**Comment by marcosgrimm** [comment]
Issues were fixed.
